name = "squirrelpack"
author = "keuerle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0f9cfca94ec0eb17aca29e083690d819f976593c2c15b50ae1ea59e99e99cd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
