name = "squirrelpack"
author = "keuerle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe47e989aa2c7946d2bfb21640e447c244a3c4f4839effb1b4a4e1ed1e1a0664"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
