name = "squirrelpack"
author = "keuerle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98372686cd7dee5a7fc175138c7b5aa4b4c3452e36a50a2c8fcd2f916cf6675c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
